version: '2'
services:
  deepweb_puller:
    container_name: deepweb-puller
    build:
      context: ./apps/deepweb-puller
      dockerfile: Dockerfile


  # server-api:
  #   container_name: server-api
  #   build:
  #     context: ./apps/server-api
  #     dockerfile: Dockerfile
  #   restart: 'on-failure'
  #   ports:
  #     - '5000:5000'
  # prometheus:
  #   image: prom/prometheus:latest
  #   restart: always
  #   volumes:
  #     - ./apps/server-api/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #   ports:
  #     - '9090:9090'
  